### ISSUE TITLE
shim 15.4 is causing problems on new Intel-based Macbooks 

### ISSUE THREAD

**Issue by mikeeq** [rhboot/shim#385] opened 2021-06-23 10:15 UTC
Hi all,

I was trying to boot latest release of Fedora 34 on my 2020 13" Macbook Pro, but when I choose to boot the livecd in builtin Mac's bootloader is not showing anything else besides black screen. Downgrading shim version to 15-8 resolves the issue. I've checked all 15.4-* packages of shim, but none of them boot correctly to grub2.

https://koji.fedoraproject.org/koji/packageinfo?packageID=14502

I'm not sure how should I debug it, so please share some information what exactly do I need to do/grab/share etc. Thanks ;)

**Comment by julian-klode** [comment] 2021-06-30 14:11
Presumably one of the known issues fixed in git. Fedora needs a new shim at some point, and we really need a new shim release.

You'll have to use `mokutil --set-verbosity true` and then capture the screen with a camera. Good luck.

**Comment by thesourcehim** [comment] 2021-07-27 11:39
I'm having similar issue on Dell 5510 laptop with shim 15.4 (Fedora 34). After I enrolled my mok, shim started to hang on boot unless secure boot is set to audit mode in bios. I.e audit mode - shim boots, deploy mode (default) - shim hangs, secure boot disabled - shim hangs

**Comment by thesourcehim** [comment] 2021-07-27 11:47
Here's shim's log with secure boot set to default mode
![IMG_20210727_144129](https://user-images.githubusercontent.com/4952491/127148339-088e7e9a-2a7e-4a9d-adc0-1e6d58b5bb12.jpg)

I can upload previous log segments if needed. After the last message (finished verifying SBAT data: success) nothing happens, this screen stays forever.

**Comment by ValdikSS** [comment] 2021-07-31 18:42
Have a black screen with infinite loop (laptop runs hot) on Lenovo ThinkPad X220, and old laptop without Secure Boot support, after updating from Fedora 33 to 34.
No prints, no anything, just black screen.
Booting grubx64 using EFI shell works fine.

Running `mokutil --set-verbosity true` says `This system doesn't support Secure Boot`.

**Comment by thesourcehim** [comment] 2021-08-03 14:41
I want to try latest git version, but I'm stuck: I have built shim and signed it according to this: https://en.opensuse.org/openSUSE:UEFI_Image_File_Sign_Tools
But bios fails to verify the signature. What am I doing wrong?

sudo pesign -n certdb -S -i /boot/efi/EFI/fedora/shimx64.efi 

certificate address is 0x7f6d61739a48
Content was not encrypted.
Content is detached; signature cannot be verified.
The signer's common name is thesource
No signer email address.
Signing time: Tue Aug 03, 2021
There were certs or crls included.

**Comment by julian-klode** [comment] 2021-08-03 14:44
Well, you'll have to set up your own CA, self-sign yourself some DB, PK, and KEK keys and configure your firmware to use those instead of the microsoft key. I guess optimally you want to merge them.

**Comment by thesourcehim** [comment] 2021-08-04 07:38
I wasn't able to test with secure boot enabled, but at least with other variants I could not reproduce the freeze with latest git version.

**Comment by thesourcehim** [comment] 2021-08-28 16:38
> Well, you'll have to set up your own CA, generate self-sign yourself some DB, PK, and KEK keys and configure your firmware to use those instead of the microsoft key. I guess optimally you want to merge them. It's a whole lot of fun!

I managed to do this following these instructions: https://habr.com/ru/post/273497/ (Russian article, use translator).
I successfully tested current git version (1b30c2b), works fine every time with secure boot enabled in deploy mode, no freezes.

**Closed** 2021-10-13 14:09 UTC

**Comment by ema** [comment] 2023-10-04 15:38
> Adding `605dab50-e046-e046-abb6-3dd810dd8b23-SHIM_VERBOSE` variable with "\x01" value with `efivar` manually produced no additional output.

For the record the GUID above is incorrect, there's a missing `4300`.

The right one is: `605dab50-e046-4300-abb6-3dd810dd8b23`, see https://sources.debian.org/src/shim/15.7-1/lib/guid.c/#L37
